// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.codedawn.vital.server.rpc;

public final class VitalRPC {
  private VitalRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VitalRpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VitalRpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.Frame frame = 2;</code>
     */
    boolean hasFrame();
    /**
     * <code>.Frame frame = 2;</code>
     */
    com.codedawn.vital.server.proto.VitalPB.Frame getFrame();
    /**
     * <code>.Frame frame = 2;</code>
     */
    com.codedawn.vital.server.proto.VitalPB.FrameOrBuilder getFrameOrBuilder();
  }
  /**
   * Protobuf type {@code VitalRpcRequest}
   */
  public  static final class VitalRpcRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VitalRpcRequest)
      VitalRpcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VitalRpcRequest.newBuilder() to construct.
    private VitalRpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VitalRpcRequest() {
      id_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VitalRpcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              com.codedawn.vital.server.proto.VitalPB.Frame.Builder subBuilder = null;
              if (frame_ != null) {
                subBuilder = frame_.toBuilder();
              }
              frame_ = input.readMessage(com.codedawn.vital.server.proto.VitalPB.Frame.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(frame_);
                frame_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codedawn.vital.server.rpc.VitalRPC.internal_static_VitalRpcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codedawn.vital.server.rpc.VitalRPC.internal_static_VitalRpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest.class, com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FRAME_FIELD_NUMBER = 2;
    private com.codedawn.vital.server.proto.VitalPB.Frame frame_;
    /**
     * <code>.Frame frame = 2;</code>
     */
    public boolean hasFrame() {
      return frame_ != null;
    }
    /**
     * <code>.Frame frame = 2;</code>
     */
    public com.codedawn.vital.server.proto.VitalPB.Frame getFrame() {
      return frame_ == null ? com.codedawn.vital.server.proto.VitalPB.Frame.getDefaultInstance() : frame_;
    }
    /**
     * <code>.Frame frame = 2;</code>
     */
    public com.codedawn.vital.server.proto.VitalPB.FrameOrBuilder getFrameOrBuilder() {
      return getFrame();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (frame_ != null) {
        output.writeMessage(2, getFrame());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (frame_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFrame());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest)) {
        return super.equals(obj);
      }
      com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest other = (com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (hasFrame() == other.hasFrame());
      if (hasFrame()) {
        result = result && getFrame()
            .equals(other.getFrame());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (hasFrame()) {
        hash = (37 * hash) + FRAME_FIELD_NUMBER;
        hash = (53 * hash) + getFrame().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VitalRpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VitalRpcRequest)
        com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.codedawn.vital.server.rpc.VitalRPC.internal_static_VitalRpcRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.codedawn.vital.server.rpc.VitalRPC.internal_static_VitalRpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest.class, com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest.Builder.class);
      }

      // Construct using com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        if (frameBuilder_ == null) {
          frame_ = null;
        } else {
          frame_ = null;
          frameBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.codedawn.vital.server.rpc.VitalRPC.internal_static_VitalRpcRequest_descriptor;
      }

      @java.lang.Override
      public com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest getDefaultInstanceForType() {
        return com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest build() {
        com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest buildPartial() {
        com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest result = new com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest(this);
        result.id_ = id_;
        if (frameBuilder_ == null) {
          result.frame_ = frame_;
        } else {
          result.frame_ = frameBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest) {
          return mergeFrom((com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest other) {
        if (other == com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.hasFrame()) {
          mergeFrame(other.getFrame());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private com.codedawn.vital.server.proto.VitalPB.Frame frame_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.codedawn.vital.server.proto.VitalPB.Frame, com.codedawn.vital.server.proto.VitalPB.Frame.Builder, com.codedawn.vital.server.proto.VitalPB.FrameOrBuilder> frameBuilder_;
      /**
       * <code>.Frame frame = 2;</code>
       */
      public boolean hasFrame() {
        return frameBuilder_ != null || frame_ != null;
      }
      /**
       * <code>.Frame frame = 2;</code>
       */
      public com.codedawn.vital.server.proto.VitalPB.Frame getFrame() {
        if (frameBuilder_ == null) {
          return frame_ == null ? com.codedawn.vital.server.proto.VitalPB.Frame.getDefaultInstance() : frame_;
        } else {
          return frameBuilder_.getMessage();
        }
      }
      /**
       * <code>.Frame frame = 2;</code>
       */
      public Builder setFrame(com.codedawn.vital.server.proto.VitalPB.Frame value) {
        if (frameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          frame_ = value;
          onChanged();
        } else {
          frameBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Frame frame = 2;</code>
       */
      public Builder setFrame(
          com.codedawn.vital.server.proto.VitalPB.Frame.Builder builderForValue) {
        if (frameBuilder_ == null) {
          frame_ = builderForValue.build();
          onChanged();
        } else {
          frameBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Frame frame = 2;</code>
       */
      public Builder mergeFrame(com.codedawn.vital.server.proto.VitalPB.Frame value) {
        if (frameBuilder_ == null) {
          if (frame_ != null) {
            frame_ =
              com.codedawn.vital.server.proto.VitalPB.Frame.newBuilder(frame_).mergeFrom(value).buildPartial();
          } else {
            frame_ = value;
          }
          onChanged();
        } else {
          frameBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Frame frame = 2;</code>
       */
      public Builder clearFrame() {
        if (frameBuilder_ == null) {
          frame_ = null;
          onChanged();
        } else {
          frame_ = null;
          frameBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Frame frame = 2;</code>
       */
      public com.codedawn.vital.server.proto.VitalPB.Frame.Builder getFrameBuilder() {
        
        onChanged();
        return getFrameFieldBuilder().getBuilder();
      }
      /**
       * <code>.Frame frame = 2;</code>
       */
      public com.codedawn.vital.server.proto.VitalPB.FrameOrBuilder getFrameOrBuilder() {
        if (frameBuilder_ != null) {
          return frameBuilder_.getMessageOrBuilder();
        } else {
          return frame_ == null ?
              com.codedawn.vital.server.proto.VitalPB.Frame.getDefaultInstance() : frame_;
        }
      }
      /**
       * <code>.Frame frame = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.codedawn.vital.server.proto.VitalPB.Frame, com.codedawn.vital.server.proto.VitalPB.Frame.Builder, com.codedawn.vital.server.proto.VitalPB.FrameOrBuilder> 
          getFrameFieldBuilder() {
        if (frameBuilder_ == null) {
          frameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.codedawn.vital.server.proto.VitalPB.Frame, com.codedawn.vital.server.proto.VitalPB.Frame.Builder, com.codedawn.vital.server.proto.VitalPB.FrameOrBuilder>(
                  getFrame(),
                  getParentForChildren(),
                  isClean());
          frame_ = null;
        }
        return frameBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VitalRpcRequest)
    }

    // @@protoc_insertion_point(class_scope:VitalRpcRequest)
    private static final com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest();
    }

    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VitalRpcRequest>
        PARSER = new com.google.protobuf.AbstractParser<VitalRpcRequest>() {
      @java.lang.Override
      public VitalRpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VitalRpcRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VitalRpcRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VitalRpcRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.codedawn.vital.server.rpc.VitalRPC.VitalRpcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VitalRpcResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VitalRpcResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code VitalRpcResponse}
   */
  public  static final class VitalRpcResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VitalRpcResponse)
      VitalRpcResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VitalRpcResponse.newBuilder() to construct.
    private VitalRpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VitalRpcResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VitalRpcResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codedawn.vital.server.rpc.VitalRPC.internal_static_VitalRpcResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codedawn.vital.server.rpc.VitalRPC.internal_static_VitalRpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse.class, com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse)) {
        return super.equals(obj);
      }
      com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse other = (com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VitalRpcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VitalRpcResponse)
        com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.codedawn.vital.server.rpc.VitalRPC.internal_static_VitalRpcResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.codedawn.vital.server.rpc.VitalRPC.internal_static_VitalRpcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse.class, com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse.Builder.class);
      }

      // Construct using com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.codedawn.vital.server.rpc.VitalRPC.internal_static_VitalRpcResponse_descriptor;
      }

      @java.lang.Override
      public com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse getDefaultInstanceForType() {
        return com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse build() {
        com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse buildPartial() {
        com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse result = new com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse) {
          return mergeFrom((com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse other) {
        if (other == com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VitalRpcResponse)
    }

    // @@protoc_insertion_point(class_scope:VitalRpcResponse)
    private static final com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse();
    }

    public static com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VitalRpcResponse>
        PARSER = new com.google.protobuf.AbstractParser<VitalRpcResponse>() {
      @java.lang.Override
      public VitalRpcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VitalRpcResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VitalRpcResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VitalRpcResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.codedawn.vital.server.rpc.VitalRPC.VitalRpcResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VitalRpcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VitalRpcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VitalRpcResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VitalRpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\032\016protocol.proto\"4\n\017VitalRpcR" +
      "equest\022\n\n\002id\030\001 \001(\t\022\025\n\005frame\030\002 \001(\0132\006.Fram" +
      "e\"\022\n\020VitalRpcResponse2@\n\017VitalRpcService" +
      "\022-\n\004send\022\020.VitalRpcRequest\032\021.VitalRpcRes" +
      "ponse\"\000B+\n\035com.codedawn.vital.server.rpc" +
      "B\010VitalRPCH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.codedawn.vital.server.proto.VitalPB.getDescriptor(),
        }, assigner);
    internal_static_VitalRpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VitalRpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VitalRpcRequest_descriptor,
        new java.lang.String[] { "Id", "Frame", });
    internal_static_VitalRpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VitalRpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VitalRpcResponse_descriptor,
        new java.lang.String[] { });
    com.codedawn.vital.server.proto.VitalPB.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
